### AssignVehicleToCustomer
POST localhost:8080/api/customers/6e1274ca-6a1a-420d-af41-d81a232a9a50/vehicles/add
Content-Type: application/json

{
        "id": "b1f2b953-9c02-46fd-8f1c-ea5a9cf9c2e7",
        "license_plate": "PGY 356",
        "brand": "Renault",
        "model": "Sandero",
        "mileage": 60000
}





