### Customer Creator
POST localhost:8080/api/customers
Content-Type: application/json

{
          "id":   "6e1274ca-6a1a-420d-af41-d81a232a9a50",
          "fullname": "John Doe",
          "email": "johndoe@gmail.com"
}
### Customer Finder
GET localhost:8080/api/customers/6e1274ca-6a1a-420d-af41-d81a232a9a50
Content-Type: application/json

### Customers Searcher
GET localhost:8080/api/customers
Content-Type: application/json