### Garage Creator
POST localhost:8080/api/garages
Content-Type: application/json

{
    "id": "2b2c5732-5e6b-4b18-8b2b-251e4a130b59",
    "name": "UNGS taller"
}

### Garage Finder
GET localhost:8080/api/garages/2b2c5732-5e6b-4b18-8b2b-251e4a130b59
Content-Type: application/json

### Garages Searcher
GET localhost:8080/api/garages
Content-Type: application/json