### Admin User Registrar
POST localhost:8080/api/users
Content-Type: application/json

{
    "id": "c0da8e9b-de9c-4134-b43a-030b1def3466",
    "type": "ADMIN",
    "username": "admin",
    "password": "123"
}

### Garage Admin User Registrar
POST localhost:8080/api/users
Content-Type: application/json

{
    "id": "8270d559-93ff-4747-85f1-6591104d956e",
    "type": "GARAGE_ADMIN",
    "username": "garage1234",
    "password": "a123",
    "garage_id": "2b2c5732-5e6b-4b18-8b2b-251e4a130b59"
}

### Mechanic User Registrar
POST localhost:8080/api/users
Content-Type: application/json

{
    "id": "3fe213b9-7848-4eac-b2dd-fb8545b8a762",
    "type": "MECHANIC",
    "username": "mechanic123",
    "password": "a123",
    "garage_id": "2b2c5732-5e6b-4b18-8b2b-251e4a130b59"
}

### User Authenticator
POST localhost:8080/api/users/authentications
Content-Type: application/json

{
    "username": "mechanic123",
    "password": "a123"
}

### User Finder
GET localhost:8080/api/users/3fe213b9-7848-4eac-b2dd-fb8545b8a762
Content-Type: application/json

### User Searcher
GET localhost:8080/api/users
Content-Type: application/json