### Vehicle Creator
POST localhost:8080/api/vehicles
Content-Type: application/json

    {
        "id": "e6406c25-e443-4238-8914-8c7ba392c785",
        "brand": "Chevrolet",
        "model": "Zafira"
    }

### Vehicle Finder
GET localhost:8080/api/vehicles/e6406c25-e443-4238-8914-8c7ba392c785
Content-Type: application/json

### Vehicles Searcher
GET localhost:8080/api/vehicles
Content-Type: application/json